"""empty message

Revision ID: 88390d3979d1
Revises: 15791a4b1d49
Create Date: 2021-12-11 13:47:02.782740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88390d3979d1'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('clima', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritoplanetas',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_planeta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planeta'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('planeta_origen', sa.Integer(), nullable=True),
    sa.Column('estatura', sa.Integer(), nullable=True),
    sa.Column('colorojos', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['planeta_origen'], ['planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritopersonajes',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_personaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personaje'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('conductor', sa.String(length=50), nullable=True),
    sa.Column('id_personaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personaje'], ['personajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritovehiculos',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_vehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.drop_index('email', table_name='user')
    op.drop_index('email_2', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='user_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email_2', 'user', ['email'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_table('favoritovehiculos')
    op.drop_table('vehiculos')
    op.drop_table('favoritopersonajes')
    op.drop_table('personajes')
    op.drop_table('favoritoplanetas')
    op.drop_table('usuario')
    op.drop_table('planetas')
    # ### end Alembic commands ###
