"""empty message

Revision ID: f2ad858ee03b
Revises: 88390d3979d1
Create Date: 2021-12-14 01:31:44.778058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ad858ee03b'
down_revision = '88390d3979d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personajes', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.drop_column('personajes', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personajes', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('personajes', 'nombre')
    # ### end Alembic commands ###
